import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:provider/provider.dart';
import 'package:my_video_project/core/logic/app_provider.dart';
import 'package:my_video_project/core/components/universal_image.dart';
import 'package:my_video_project/core/services/remote_config_service.dart';
import 'package:my_video_project/presentation/details/components/lazy_horizontal_section.dart';
import 'package:my_video_project/presentation/notifications/notifications_screen.dart' deferred as notif_page;
import 'package:my_video_project/presentation/details/movie_details_screen.dart' deferred as details_page;

class HomeScreen extends StatelessWidget { const HomeScreen({super.key}); void _handleVisit(BuildContext context, String targetId, bool isExternal, String? externalUrl) async { if (isExternal && externalUrl != null) { launchUrl(Uri.parse(externalUrl)); } else if (RemoteConfigService.moviesDb.containsKey(targetId)) { await details_page.loadLibrary(); if (context.mounted) Navigator.push(context, MaterialPageRoute(builder: (_) => details_page.MovieDetailsScreen(movie: RemoteConfigService.moviesDb[targetId]!))); } } @override Widget build(BuildContext context) { final p = Provider.of<AppProvider>(context); final hero = RemoteConfigService.heroData; final sections = RemoteConfigService.homeSections; return Scaffold(extendBodyBehindAppBar: true, appBar: AppBar(backgroundColor: Colors.transparent, elevation: 0, leading: RemoteConfigService.appLogoUrl != null ? Padding(padding: const EdgeInsets.all(8.0), child: UniversalImage(path: RemoteConfigService.appLogoUrl!, fit: BoxFit.contain)) : const SizedBox.shrink(), actions: [IconButton(icon: const Icon(Icons.notifications_none, color: Colors.white), onPressed: () async { await notif_page.loadLibrary(); if (context.mounted) Navigator.push(context, MaterialPageRoute(builder: (_) => notif_page.NotificationsScreen())); }), const SizedBox(width: 8)]), body: SingleChildScrollView(child: Column(children: [if (hero != null) SizedBox(height: MediaQuery.of(context).size.height * 0.6, width: double.infinity, child: Stack(fit: StackFit.expand, children: [Container(color: const Color(0xFF1A1A1A), child: UniversalImage(path: hero.posterUrl, fit: BoxFit.cover)), Container(decoration: const BoxDecoration(gradient: LinearGradient(colors: [Colors.black, Colors.transparent], begin: Alignment.bottomCenter, end: Alignment.center))), Positioned(bottom: 40, left: 20, right: 20, child: Column(crossAxisAlignment: CrossAxisAlignment.center, children: [Text(hero.title, style: const TextStyle(color: Colors.white, fontSize: 32, fontWeight: FontWeight.bold), textAlign: TextAlign.center), const SizedBox(height: 16), ElevatedButton.icon(onPressed: () => _handleVisit(context, hero.targetId, hero.isExternal, hero.externalUrl), icon: const Icon(Icons.north_east, color: Colors.black, size: 16), label: Text(p.tr('visit')), style: ElevatedButton.styleFrom(backgroundColor: Colors.white, foregroundColor: Colors.black, padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 12)))]))])), const SizedBox(height: 24), ...sections.map((sec) => Padding(padding: const EdgeInsets.only(bottom: 24.0), child: LazyHorizontalSection(title: sec.title, showTitles: sec.showTitles, initialMovies: sec.items, onLoadMore: () async => []))), const SizedBox(height: 40)]))); } }
