import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:provider/provider.dart';
import 'package:my_video_project/core/logic/app_provider.dart';
import 'package:my_video_project/core/components/universal_image.dart';
import 'package:my_video_project/data/models/movie_models.dart';
import 'package:my_video_project/data/mock_data.dart';
import 'package:my_video_project/presentation/details/components/lazy_horizontal_section.dart';
import 'package:my_video_project/presentation/details/movie_details_screen.dart';
import 'package:my_video_project/presentation/notifications/notifications_screen.dart';
class HomeScreen extends StatelessWidget { const HomeScreen({super.key}); static const Map<String, dynamic> _heroData = { 'title': 'Flutter Series', 'isExternalAd': false, 'externalUrl': 'https://google.com' }; void _handleVisit(BuildContext context) { if (_heroData['isExternalAd']) { launchUrl(Uri.parse(_heroData['externalUrl'])); } else { Navigator.push(context, MaterialPageRoute(builder: (_) => MovieDetailsScreen(movie: MockData.allMovies.first))); } } @override Widget build(BuildContext context) { final p = Provider.of<AppProvider>(context); return Scaffold(extendBodyBehindAppBar: true, appBar: AppBar(backgroundColor: Colors.transparent, elevation: 0, actions: [IconButton(icon: const Icon(Icons.notifications_none, color: Colors.white), onPressed: () => Navigator.push(context, MaterialPageRoute(builder: (_) => const NotificationsScreen()))), const SizedBox(width: 16)]), body: SingleChildScrollView(child: Column(children: [SizedBox(height: MediaQuery.of(context).size.height * 0.6, width: double.infinity, child: Stack(fit: StackFit.expand, children: [const UniversalImage(path: "https://via.placeholder.com/1920x1080?text=Featured+Content", fit: BoxFit.cover), Container(decoration: const BoxDecoration(gradient: LinearGradient(colors: [Colors.black, Colors.transparent], begin: Alignment.bottomCenter, end: Alignment.center))), Positioned(bottom: 40, left: 20, right: 20, child: Column(crossAxisAlignment: CrossAxisAlignment.center, children: [Text(_heroData['title'], style: const TextStyle(color: Colors.white, fontSize: 32, fontWeight: FontWeight.bold), textAlign: TextAlign.center), const SizedBox(height: 16), ElevatedButton.icon(onPressed: () => _handleVisit(context), icon: const Icon(Icons.north_east, color: Colors.black, size: 16), label: Text(p.tr('visit')), style: ElevatedButton.styleFrom(backgroundColor: Colors.white, foregroundColor: Colors.black, padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 12)))]))])), const SizedBox(height: 24), _sec(p.tr('trending')), const SizedBox(height: 24), _sec(p.tr('new_releases')), const SizedBox(height: 40)]))); } Widget _sec(String t) => LazyHorizontalSection(title: t, initialMovies: MockData.allMovies.map((m) => MovieSnippet(id: m.id.toString(), imageUrl: m.posterPath, title: m.title)).toList(), onLoadMore: () async => []); }
