import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:my_video_project/core/logic/app_provider.dart';
import 'package:my_video_project/core/components/universal_image.dart';
import 'package:my_video_project/core/theme/app_colors.dart';
import 'package:my_video_project/data/models/movie_models.dart';
import 'package:my_video_project/core/services/remote_config_service.dart';
import 'package:my_video_project/presentation/details/movie_details_screen.dart' deferred as details_page;
class SearchScreen extends StatefulWidget { const SearchScreen({super.key}); @override State<SearchScreen> createState() => _S(); }
class _S extends State<SearchScreen> { List<MovieSnippet> _filt = []; @override void initState() { super.initState(); _filt = RemoteConfigService.searchSuggestions; } void _run(String k) => setState(() => _filt = k.isEmpty ? RemoteConfigService.searchSuggestions : RemoteConfigService.allSnippets.where((e) => e.title.toLowerCase().contains(k.toLowerCase())).toList()); @override Widget build(BuildContext context) { final p = Provider.of<AppProvider>(context); return Scaffold(backgroundColor: AppColors.background, appBar: AppBar(title: Text(p.tr('search')), centerTitle: true, backgroundColor: Colors.transparent, elevation: 0, leading: BackButton(color: Colors.white, onPressed: () { if (p.navIndex != 0) { p.setNavIndex(0); } else { Navigator.pop(context); } })), body: Padding(padding: const EdgeInsets.all(16), child: Column(children: [TextField(onChanged: _run, style: const TextStyle(color: Colors.white), decoration: InputDecoration(hintText: p.tr('search'), hintStyle: const TextStyle(color: Colors.grey), prefixIcon: const Icon(Icons.search, color: Colors.grey), filled: true, fillColor: const Color(0xFF202020), border: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: BorderSide.none))), const SizedBox(height: 20), Expanded(child: LayoutBuilder(builder: (c, cs) { int cnt = (cs.maxWidth / 150).floor().clamp(3, 8); double itemW = (cs.maxWidth - (cnt - 1) * 16) / cnt; double itemH = (itemW * 1.5) + 65; double ratio = itemW / itemH; return GridView.builder(padding: const EdgeInsets.only(bottom: 120), gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount: cnt, childAspectRatio: ratio, crossAxisSpacing: 16, mainAxisSpacing: 16), itemCount: _filt.length, itemBuilder: (c, i) => InkWell(onTap: () async { if(RemoteConfigService.moviesDb.containsKey(_filt[i].id)) { await details_page.loadLibrary(); if(context.mounted) Navigator.push(c, MaterialPageRoute(builder: (_) => details_page.MovieDetailsScreen(movie: RemoteConfigService.moviesDb[_filt[i].id]!))); } }, child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [ClipRRect(borderRadius: BorderRadius.circular(8), child: Container(color: const Color(0xFF1A1A1A), child: UniversalImage(path: _filt[i].imageUrl))), const SizedBox(height: 8), Text(_filt[i].title, maxLines: 2, overflow: TextOverflow.ellipsis, style: const TextStyle(color: Colors.white, fontSize: 13))]))); }))]))); } }
