class AppStrings {
  static const Map<String, Map<String, String>> _values = {
    'en': {
      'home': 'Home', 'search': 'Search', 'list': 'My List', 'settings': 'Settings',
      'watch': 'Watch', 'notifications': 'Notifications', 'trending': 'Trending',
      'new_releases': 'New Releases', 'view_all': 'View All', 'show_more': 'Show More',
      'show_less': 'Show Less', 'autoplay': 'Autoplay', 'visit': 'Visit',
      'clear_cache': 'Clear Cache', 'about_app': 'About App', 'language': 'Language',
      'auto': 'Auto', 'en': 'English', 'ar': 'العربية', 'es': 'Spanish', 'fr': 'French',
      'content_note': 'Content Note', 'content_desc': 'Viewer discretion is advised.',
      'close': 'Close', 'close_ad': 'Close AD',
      'cache_cleared': 'Cache cleared successfully', 'protected': 'Protected',
      'connection_error': 'Connection Lost', 'retry': 'Retry', 'episodes': 'Episodes',
      'overview': 'Overview', 'recommendations': 'Recommendations',
      'speed': 'Speed', 'quality': 'Quality', 'subtitles': 'Subtitles', 
      'disable': 'Off', 'back': 'Back',
      'wait_msg': 'Recording protection active. Please wait...',
      'reminder_set': 'Reminder set successfully!',
      'added_list': 'Added to My List',
      'removed_list': 'Removed from My List',
      'empty_list': 'Your list is empty',
      'report_subject': 'Report Content: ',
      'link_fail': 'Link failed, trying next...',
      'cooling_down': 'Network unstable. Retrying...',
      'cache_limit': 'Cache clear limit reached (3/day). Please wait 24h.',
      'resume_msg': 'Do you want to resume the video from where you left off?',
      'resume_btn': 'Resume'
    },
    'ar': {
      'home': 'الرئيسية', 'search': 'البحث', 'list': 'قائمتي', 'settings': 'الإعدادات',
      'watch': 'مشاهدة', 'notifications': 'الإشعارات', 'trending': 'الأكثر رواجاً',
      'new_releases': 'الإصدارات الجديدة', 'view_all': 'عرض الكل', 'show_more': 'عرض المزيد',
      'show_less': 'عرض أقل', 'autoplay': 'تشغيل تلقائي', 'visit': 'زيارة',
      'clear_cache': 'مسح الذاكرة المؤقتة', 'about_app': 'حول التطبيق', 'language': 'اللغة',
      'auto': 'تلقائي', 'en': 'English', 'ar': 'العربية', 'es': 'Spanish', 'fr': 'French',
      'content_note': 'ملاحظة المحتوى', 'content_desc': 'يرجى توخي الحذر عند المشاهدة.',
      'close': 'إغلاق', 'close_ad': 'إغلاق الإعلان',
      'cache_cleared': 'تم مسح الذاكرة بنجاح', 'protected': 'محتوى محمي',
      'connection_error': 'انقطع الاتصال', 'retry': 'إعادة المحاولة', 'episodes': 'الحلقات',
      'overview': 'نبذة', 'recommendations': 'توصيات',
      'speed': 'السرعة', 'quality': 'الجودة', 'subtitles': 'الترجمة',
      'disable': 'إيقاف', 'back': 'رجوع',
      'wait_msg': 'حماية التسجيل نشطة. يرجى الانتظار...',
      'reminder_set': 'تم ضبط التذكير بنجاح!',
      'added_list': 'تمت الإضافة إلى قائمتي',
      'removed_list': 'تمت الإزالة من قائمتي',
      'empty_list': 'قائمتك فارغة',
      'report_subject': 'إبلاغ عن محتوى: ',
      'link_fail': 'فشل الرابط، جارٍ تجربة التالي...',
      'cooling_down': 'الشبكة غير مستقرة. سنحاول بعد قليل...',
      'cache_limit': 'تم الوصول للحد الأقصى لمسح الذاكرة (3/يومياً). يرجى الانتظار 24 ساعة.',
      'resume_msg': 'هل تريد استئناف الفديو من حيث توقفت',
      'resume_btn': 'أستئناف'
    }
  };
  static String get(String code, String key) => _values[code]?[key] ?? key;
}
